import type { TypographyPreset } from '../types/hymns.ts';

export const HYMN_TYPOGRAPHY_PRESETS: TypographyPreset[] = [
  {
    id: 'classic-worship-serif',
    label: 'Classic Worship Serif',
    description: 'Warm serif presentation for congregational hymns and reflective services.',
    fontCategory: 'serif',
    fontFamily: 'Georgia, Cambria, "Times New Roman", serif',
    fallbackFontFamily: 'serif',
    fontSizeToken: 'large',
    lineHeight: 1.15,
    alignment: 'center',
    caseTransform: 'none',
    outlineStrength: 1.4,
    letterSpacing: 0.2,
    safeAreaBehavior: 'standard',
    bodyFrame: { x: 0.12, y: 0.2, width: 0.76, height: 0.54 },
    labelFrame: { x: 0.34, y: 0.08, width: 0.32, height: 0.08 },
    textColor: '#F8F4EC',
    labelColor: '#F2D8A7',
    shadow: true,
  },
  {
    id: 'modern-clean-sans',
    label: 'Modern Clean Sans',
    description: 'Minimal, crisp lyric look for youth and broadcast-led environments.',
    fontCategory: 'sans',
    fontFamily: '"Avenir Next", "Segoe UI", Helvetica, Arial, sans-serif',
    fallbackFontFamily: 'sans-serif',
    fontSizeToken: 'large',
    lineHeight: 1.1,
    alignment: 'center',
    caseTransform: 'none',
    outlineStrength: 1.2,
    letterSpacing: 0.35,
    safeAreaBehavior: 'wide',
    bodyFrame: { x: 0.1, y: 0.22, width: 0.8, height: 0.5 },
    labelFrame: { x: 0.3, y: 0.08, width: 0.4, height: 0.08 },
    textColor: '#F9FAFB',
    labelColor: '#7DD3FC',
    shadow: true,
  },
  {
    id: 'choir-hymnal',
    label: 'Choir / Hymnal',
    description: 'Denser hymn-book inspired layout that still preserves stage readability.',
    fontCategory: 'hymnal',
    fontFamily: '"Palatino Linotype", "Book Antiqua", Georgia, serif',
    fallbackFontFamily: 'serif',
    fontSizeToken: 'medium',
    lineHeight: 1.22,
    alignment: 'center',
    caseTransform: 'none',
    outlineStrength: 1,
    letterSpacing: 0.12,
    safeAreaBehavior: 'choir',
    bodyFrame: { x: 0.16, y: 0.18, width: 0.68, height: 0.56 },
    labelFrame: { x: 0.36, y: 0.07, width: 0.28, height: 0.08 },
    textColor: '#FAF7F2',
    labelColor: '#D6BCFA',
    shadow: true,
  },
  {
    id: 'big-hall-readability',
    label: 'Big Hall Readability',
    description: 'High-contrast preset for larger auditoriums and rear-screen visibility.',
    fontCategory: 'sans',
    fontFamily: '"Franklin Gothic Medium", "Arial Narrow", "Segoe UI", sans-serif',
    fallbackFontFamily: 'sans-serif',
    fontSizeToken: 'xlarge',
    lineHeight: 1.08,
    alignment: 'center',
    caseTransform: 'uppercase',
    outlineStrength: 2.1,
    letterSpacing: 0.75,
    safeAreaBehavior: 'wide',
    bodyFrame: { x: 0.08, y: 0.23, width: 0.84, height: 0.46 },
    labelFrame: { x: 0.28, y: 0.08, width: 0.44, height: 0.08 },
    textColor: '#FFFFFF',
    labelColor: '#FDE68A',
    shadow: true,
  },
  {
    id: 'broadcast-lower-third-worship',
    label: 'Broadcast Lower Third Worship',
    description: 'Lower-third optimized hymn preset for stream overlays and hybrid broadcasts.',
    fontCategory: 'broadcast',
    fontFamily: '"Avenir Next Condensed", "Segoe UI", Helvetica, Arial, sans-serif',
    fallbackFontFamily: 'sans-serif',
    fontSizeToken: 'medium',
    lineHeight: 1.05,
    alignment: 'center',
    caseTransform: 'uppercase',
    outlineStrength: 2.4,
    letterSpacing: 0.9,
    safeAreaBehavior: 'lower-third',
    bodyFrame: { x: 0.14, y: 0.62, width: 0.72, height: 0.2 },
    labelFrame: { x: 0.38, y: 0.52, width: 0.24, height: 0.06 },
    textColor: '#FFFFFF',
    labelColor: '#FCA5A5',
    shadow: true,
  },
];

export const DEFAULT_HYMN_TYPOGRAPHY_PRESET_ID = HYMN_TYPOGRAPHY_PRESETS[0]?.id || 'classic-worship-serif';

export const getTypographyPreset = (presetId?: string): TypographyPreset => (
  HYMN_TYPOGRAPHY_PRESETS.find((entry) => entry.id === presetId)
  || HYMN_TYPOGRAPHY_PRESETS[0]
);
